apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: support-chat-backend-stage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/sujanustc/ostad-capstan-backend.git'
    targetRevision: stage
    path: k8s/stage
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: stage
  syncPolicy: {}
