apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: support-chat-backend-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/sujanustc/ostad-capstan-backend.git'
    targetRevision: prod
    path: k8s/prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
